### ISSUE TITLE
about pim

### ISSUE THREAD

**Issue by mingtaojia** [compmech/meshless#1]
Dir sir: 
     according to this"from pim.composite.laminate import read_stack", maybe pim was an package, and where to download it, thanks.

**Comment by saullocastro** [comment]
Dear @mingtaojia  it should be `from meshless.composite.laminate import read_stack`.  The name `pim` was only temporary. Could you please point out where did you read it? It must be fixed...

**Comment by mingtaojia** [comment]
Dir @saullocastro ,  it was found in the file 'sfem_tria3_example.py' and in the directory "theory"

**Comment by saullocastro** [comment]
@mingtaojia  I fixed the files, thanks. Feel free to reopen if you have any troubles
